import Head from 'next/head'
import React from 'react'

const HeadMeta = (props) => {
   return (
      <Head>
         <meta charSet="UTF-8" />
         <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
         <meta name="description" content="Generated by create next app" />
         <title>{props.title}</title>
         <link rel="icon" href="/favicon.png" />
      </Head>
   )
}

export default HeadMeta;